{
 "title": "HPA Custom Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Nodes by Zone",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (label_failure_domain_beta_kubernetes_io_zone) (kube_node_labels)",
     "legendFormat": "{{label_failure_domain_beta_kubernetes_io_zone}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod, instance) (rate(myapp_response_time_count[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Application Instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\"hpa-sim-.*\"})"
    }
   ]
  },
  {
   "title": "Total Active Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(myapp_client_connected)" }
   ]
  },
  {
   "title": "Active Connections per Instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance) (myapp_client_connected)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod, instance) (irate(process_cpu_seconds_total{pod=~\"hpa-sim-.*\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod, instance)(process_resident_memory_bytes{pod=~\"hpa-sim-.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}