apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hpa-sim
  labels:
    release: prometheus-operator
    app: hpa-sim
spec:
  endpoints:
  - port: http
    path: '/metrics'
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: hpa-sim
